### ISSUE TITLE
`Collection.m` still has some of the business logic from the PetroFeed app || Adding Collection#parse method

### ISSUE THREAD

**Issue by glesperance** [glesperance/chocobo#8]
`Collection.m` still has some of the business logic from the PetroFeed app (see [collection.m line 35](https://github.com/PetroFeed/chocobo/blob/master/Classes/ios/Collection.m#L35))

Perhaps the PetroFeed business specific logic could be removed and Chocobo be extended to add a `parse` method to the Collection object. (Defaulting to the identify function)

This method could then be used to implement similar behaviour in apps using Chocobo.

For reference : [`Collection#parse` documentation of backbone.js](http://backbonejs.org/#Collection-parse)

**Comment by markhazlett** [comment]
@glensperance - absolutely! I will fix this up ASAP. I agree with going with the backbone parse on this.

**Comment by markhazlett** [comment]
@glesperance - I have pushed a fix for that issue by adding another function to Collection.m(rootKey) however I'm not super happy with how that works yet. There may also be some weirdness with the repo since adding tests in a seperate xcodeproj was a pain. I'll be modifying it again most likely and then putting out another chocobo version. Stay tuned.

**Comment by glesperance** [comment]
@markhazlett Just issued  pull request #11 implementing the parse method.

This should allow more complex JSON parsing for when we need more than just getting the content of a key.

Let me know what you think !

**Comment by markhazlett** [comment]
This issue should be closed now with PR #11 - Thanks Gabriel!
